### Saving config ###
path2save: /mnt/disk1/rklokov/code/VoronoiLearning/NeuralNetworks/models/
model_name: SDFEnc_ME_64g_256l_VCDec_32c_256l_256g_1vgpp.pkl

### Dataset config ###
tr_obj_dir: /mnt/disk1/rklokov/ABC/sampleABC/Tr/obj
tr_surf_dir: /mnt/disk1/rklokov/ABC/sampleABC/Tr/surf
tr_sdf_dir: /mnt/disk1/rklokov/ABC/sampleABC/Tr/sdf64
tr_vgocc_dir: /mnt/disk1/rklokov/ABC/sampleABC/Tr/vgocc64_32p_256l_256g

val_obj_dir: /mnt/disk1/rklokov/ABC/sampleABC/Val/obj
val_surf_dir: /mnt/disk1/rklokov/ABC/sampleABC/Val/surf
val_sdf_dir: /mnt/disk1/rklokov/ABC/sampleABC/Val/sdf64
val_vgocc_dir: /mnt/disk1/rklokov/ABC/sampleABC/Val/vgocc64_32p_256l_256g

input_type: sdf
grid_size: 64
v_start: -0.5
v_end: 0.5
n_input_pc: 4096
knn_input: 8
local_input: True
pooling_radius: 1
truncate_sdf: True
truncation_cell_dist: 2
sparse_sdf: True
sample_grid_points: False
sample_grid_size: 2048
sample_grid_add_noise: False
sample_grid_add_noise_scale: 2.0
sample_gt_pc: False
n_gt_pc: 100000

### Input point cloud transformations config ###
cloud_gaussian_noise: False
cloud_gaussian_noise_scale: 0.01

### Sample transformations config ###
sample_rescale: True
sample_rescale_scale: 2.0
sample_axes_permutation: False
sample_axes_flip: False

### Data loader config ###
batch_size: 32
num_workers: 32

### Feature extractor config ###
in_dim: 1
enc_feat_dim:
  - 64
  - 128
  - 128
  - 256

### VC network config ###
vcdec_feat_dim: 
  - 512
  - 256
  - 256
vcdec_in_glob: True
vcdec_vc_per_query: 1
vcdec_vc_tanh: False
vcdec_vc_tanh_scale: 3.0
vcdec_p_dim: 3
vcdec_pe: True
vcdec_pe_feat_dim: 32
vcdec_film: False
vcdec_film_std: 0.001

### Optimizer config ###
n_epochs: 80
lr: 0.000016
wd: 0.0001
beta1: 0.9
beta2: 0.93
amsgrad: True
